server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    password: root
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update